### ISSUE TITLE
recent problems

### ISSUE THREAD

**Issue by YuhaoDuuu** [AguaClara/2_stage_coag_addition#19]
In this week and last week, we conducted several trials of 1 stage addition experiment. Several problems happened and remain unsolved. First, it's the high effluent turbidity, the effluent turbidity in last semester was usually between 5-10NTU, but this semester, we actually used a higher coag dosage but the lowest NTU only reached around 11, and for other trials, it was around 12-15. Second, this problem might relate to the first one, our coagulant solution is cloudy since last week, even we have already washed and refilled it for several times. This might require us to make some new lab concentration PAC. The last issue is about the CC, after last Sunday the system was shut down for a while, the water level in CC kept low in this week, lower than the past few weeks.

**Comment by YuhaoDuuu** [comment]
@ChingPangggg @barbaraoramah @monroews

**Comment by monroews** [comment]
Sounds like we should get a fresh batch of Coagulant from the Cornell Water Filtration plant. 
@caseyching13 please contact Christopher Lynn Bordlemay Padilla and see if you can get a small batch of coagulant. Perhaps don't get as large a volume given the concern that it might have a limited shelf life.

I believe we discussed the problem with the contact chamber previously. You need to provide a way for the air in the CC to leave the system. If you are still using a downflow system then there is no way for the air to leave. Switch to an upflow system for the CCs so that the air is pumped out.

**Comment by caseyching13** [comment]
@YuhaoDuuu @monroews I'll get the fresh coagulant to the lab by the beginning of next week!

**Comment by caseyching13** [comment]
@YuhaoDuuu Batch of coagulant has been acquired and is in the chemical section of the cabinet!

![20180324_104528](https://user-images.githubusercontent.com/25238858/37868628-0be834d4-2f80-11e8-8e24-6d843900fbfd.jpg)

**Comment by ChingPangggg** [comment]
@caseyching13 could you tell us the concentration of the coagulant? it is not labeled

**Comment by caseyching13** [comment]
@ChingPangggg Contact Christopher Lynn Bordlemay Padilla <clb83@cornell.edu> to find out! After you do, you can label the bottles with the concentration of the coagulant.

**Comment by monroews** [comment]
@WPennock can help with any calculations that are needed. Unfortunately the chemical industry uses archaic methods of reporting concentrations and thus converting the reported concentration to an intelligible concentration of aluminum is a multiple step process.
